# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-15 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kPay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
