# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kPay', '0003_auto_20180815_0046'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='worker',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='worker',
            name='commerce',
        ),
    ]
