# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kPay', '0004_auto_20180815_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='commerce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commerce', to='kPay.Commerce'),
        ),
        migrations.AlterUniqueTogether(
            name='worker',
            unique_together=set([('ci', 'commerce')]),
        ),
    ]
